server:
  port: ${HOST_PORT:8080}
  servlet:
    context-path: /manipulacao_arquivos


spring:
  application:
    name: manipulacao_arquivos
  profiles:
    active: local
#    include:
#      - dev-config
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
#  jpa:
#    hibernate.ddl-auto: none
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        temp:
#          use_jdbc_metadata_defaults: false
#    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
#  datasource:
#    url: jdbc:postgresql://localhost:5432/planilha_financeira
#    username: user_pf
#    password: pass_pf
#    driver-class-name: org.postgresql.Driver


logging:
  level:
    org.springframework.security: DEBUG
    br.com.planilhaFinanceira: DEBUG


#spring.thymeleaf.prefix=/templates/

#security.headers.hsts=NONE
#security.user.name=admin
#security.user.password=admin
#security.basic.enabled=false

#mysql.url=${MYSQL_URL:jdbc:mysql://localhost:3306/bd_financeiro}
#mysql.username=${MYSQL_USERNAME:user_financeiro}
#mysql.password=${MYSQL_PASSWORD:pass_financeiro}





